eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/

spring:
  cloud:
    config:
      overrideSystemProperties: false