spring:

  data:
    mongodb:
      username: gallagher
      password: gallagher09
      port: 27017
      additional-hosts: localhost
      database: customer
      authentication-database: admin

springdoc:
  api-docs:
    path: /customers/api-docs

    
server:
  port: 8090