spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: gallagher
    password: gallagher09
    driverClassName: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto:  validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baselineOnMigrate: true
    enabled: true
    baselineDescription: "Init"
    baselineVersion: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

    
springdoc:
  api-docs:
    path: /products/api-docs

server:
  port: 8050